# Generated by Django 3.0.7 on 2020-06-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussione',
            old_name='autore',
            new_name='autore_discussione',
        ),
    ]
