# Generated by Django 3.0.6 on 2020-08-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200630_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autore_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discussione',
        ),
        migrations.DeleteModel(
            name='Discussione',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
