# Generated by Django 3.0.6 on 2020-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200815_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='sezione',
            name='citta',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sezione',
            name='indirizzo',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sezione',
            name='provincia',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
