# Generated by Django 3.0.6 on 2020-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200815_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sezione',
            name='citta',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='indirizzo',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='provincia',
            field=models.CharField(default='', max_length=80),
        ),
    ]
