# Generated by Django 3.0.6 on 2020-08-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200815_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sezione',
            options={},
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.Sezione')),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
    ]
