# Generated by Django 3.0.6 on 2020-08-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200815_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='SezioneImage',
        ),
        migrations.RenameField(
            model_name='sezioneimage',
            old_name='image',
            new_name='logo_sezione',
        ),
    ]
