# Generated by Django 3.1 on 2020-08-19 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0011_auto_20200819_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='sezione',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.user'),
            preserve_default=False,
        ),
    ]
