# Generated by Django 3.1 on 2020-08-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200819_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sezione',
            name='user',
        ),
    ]
