# Generated by Django 3.1 on 2020-08-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20200820_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='discussione',
            new_name='sezione',
        ),
    ]
