# Generated by Django 3.1 on 2020-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20200820_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
