# Generated by Django 3.1 on 2020-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
