# Generated by Django 3.1 on 2020-08-30 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20200821_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sezione',
            name='Agriturismo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sezione',
            name='CasaVacanza',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sezione',
            name='FastFood',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sezione',
            name='Hotel',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sezione',
            name='Ristorante',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='logo_sezione',
            field=models.ImageField(null=True, upload_to='', verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='nome_sezione',
            field=models.CharField(max_length=80, verbose_name='Nome Località'),
        ),
    ]
