# Generated by Django 3.0.6 on 2020-08-30 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0021_auto_20200821_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='logo_sezione',
            field=models.ImageField(null=True, upload_to='', verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='nome_sezione',
            field=models.CharField(max_length=80, verbose_name='Nome Località'),
        ),
    ]
