# Generated by Django 3.1 on 2020-08-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20200830_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sezione',
            old_name='Agriturismo',
            new_name='agriturismoB',
        ),
        migrations.RenameField(
            model_name='sezione',
            old_name='CasaVacanza',
            new_name='casaVacanzaB',
        ),
        migrations.RenameField(
            model_name='sezione',
            old_name='FastFood',
            new_name='fastFoodB',
        ),
        migrations.RenameField(
            model_name='sezione',
            old_name='Hotel',
            new_name='hotelB',
        ),
        migrations.RenameField(
            model_name='sezione',
            old_name='Ristorante',
            new_name='ristoranteB',
        ),
    ]
