# Generated by Django 3.1 on 2020-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20200830_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='sezione',
            name='tipo',
            field=models.TextField(default='', null=True),
        ),
    ]
