# Generated by Django 3.1 on 2020-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_sezione_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sezione',
            name='agriturismoB',
            field=models.BooleanField(verbose_name='agriturismo'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='casaVacanzaB',
            field=models.BooleanField(verbose_name='casaVacanza'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='fastFoodB',
            field=models.BooleanField(verbose_name='fastFood'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='hotelB',
            field=models.BooleanField(verbose_name='hotel'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='ristoranteB',
            field=models.BooleanField(verbose_name='ristorante'),
        ),
    ]
