# Generated by Django 3.1 on 2020-09-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_auto_20200830_1922'),
        ('forum', '0022_auto_20200830_1738'),
    ]

    operations = [
    ]
