# Generated by Django 3.1 on 2020-09-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_merge_20200905_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sezione',
            name='tipo',
        ),
    ]
