# Generated by Django 3.1 on 2020-09-07 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0027_remove_sezione_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataReccomandation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.PositiveIntegerField()),
                ('ristorante', models.PositiveIntegerField()),
                ('fastFood', models.PositiveIntegerField()),
                ('casaVacanza', models.PositiveIntegerField()),
                ('agriturismo', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
